---
- hosts: sensu_server_client
  user: ubuntu
  vars:
    - sensu_install_server: true
    - sensu_install_client: true
    - sensu_client_hostname: "sensu-server-client"
    - sensu_client_address: "52.0.51.223"
  vars_files:
    - test-vars.yml
  roles:
    - redis
    - RabbitMQ
    - sensu

- hosts: sensu_server
  user: ubuntu
  vars:
    - sensu_install_server: true
    - sensu_install_client: false
  vars_files:
    - test-vars.yml
  roles:
    - redis
    - sensu

- hosts: sensu_client
  user: ubuntu
  vars:
    - sensu_install_server: false
    - sensu_install_client: true
    - sensu_client_hostname: "sensu-client"
    - sensu_client_address: "52.0.51.223"
  vars_files:
    - test-vars.yml
  roles:
    - sensu
